#!/usr/bin/env bash

function getFullDomainFromUrl {
    local url="$1"
    echo "$url" | sed -e 's|^[^/]*//||' -e 's|/.*$||'
}

function getDomainFromFullDomain {
    local domain="$1"
    echo "$url" | rev | cut -d"." -f1,2 | rev
}

function getIpFromDomain {
    local domain="$1"
    dig A +short "$domain"
}

