#!/usr/bin/env bash

function getFullDomainFromUrl {
    local url="$1"
    echo "$url" | sed -e 's|^[^/]*//||' -e 's|/.*$||' | rev | cut -d"@" -f1 | rev
}

function getDomainFromFullDomain {
    local domain="$1"
    echo "$domain" | rev | cut -d"." -f1,2 | rev
}

function getIpFromDomain {
    local domain="$1"
    dig A +short "$domain" | tail -1
}

function getNameserver {
    local domain=$(getDomainFromFullDomain "$1")
    local nameserver=$(host -t NS "$domain" | rev | cut -d" " -f1 | rev | sed 's/\.$//' | sort -u)

    if [ "$nameserver" != "" ]; then
        echo "$nameserver"
        return 0
    fi

    echo "Unknown"
    return 1
}

function getProviderFromIP {
    local ip="$1"
    whois "$ip" | grep --color=never "descr:" | head -1 | cut -d":" -f2 | xargs
}

