#!/usr/bin/env bash

function getFullDomainFromUrl {
    local url="$1"
    echo "$url" | sed -e 's|^[^/]*//||' -e 's|/.*$||' | rev | cut -d"@" -f1 | rev
}

function getDomainFromFullDomain {
    local domain="$1"
    echo "$domain" | rev | cut -d"." -f1,2 | rev
}

function getIpFromDomain {
    local domain="$1"
    dig A +short "$domain" | tail -1
}

function getNameserver {
    local domain=$(getDomainFromFullDomain "$1")
    whois "$domain" | grep "Nserver" | cut -d" " -f2
}

function getProviderFromIP {
    local ip="$1"
    whois "$ip" | grep --color=never "descr:" | head -1 | cut -d":" -f2 | xargs
}

